server:
  port: 2000

spring:
  cloud:
    gateway:
      routes:
        - id: userCmdApi-RegisterUser
          uri: http://localhast:8081/api/v1/registerUser
          predicates:
            - Path=/api/v1/registerUser

        - id: userCmdApi-UpdateUser
          uri: http://localhast:8081/api/v1/updateUser/**
          predicates:
              - Path=/api/v1/updateUser/**

        - id: userCmdApi-RemoveUser
          uri: http://localhast:8081/api/v1/removeUser/**
          predicates:
              - Path=/api/v1/removeUser/**

        - id: userQueryAPI
          uri: http://localhast:8082/api/v1/userLookup/**
          predicates:
              - Path=/api/v1/userLookup/**

        - id: bankAccCmdApi-OpenAccount
          uri: http://localhast:9091/api/v1/openBankAccount
          predicates:
            - Path=/api/v1/openBankAccount

        - id: bankAccCmdApi-DepositFunds
          uri: http://localhast:9091/api/v1/depositFunds/**
          predicates:
            - Path=/api/v1/depositFunds/**

        - id: bankAccCmdApi-WithdrawFunds
          uri: http://localhast:9091/api/v1/withdrawFunds/**
          predicates:
            - Path=/api/v1/withdrawFunds/**

        - id: bankAccCmdApi-CloseBankFunds
          uri: http://localhast:9091/api/v1/closeBankAccount/**
          predicates:
            - Path=/api/v1/closeBankAccount/**